### PR TITLE
Enable to estimate a model without externality terms

### LINKED ISSUE #2: Exception when using networks without externalities
If you use `simulate_hergm` to simulate networks without externalities, an exception gets raised.
For example, the following formula:
```
g ~ edges + nodematch('x')
```
This raises the following exception:
```
parse(text = x, keep.source = FALSE) でエラー: 
  <text>:2:0:  想定外の入力の終端です 
1: seed_network_within ~ 
   ^
```
I guess it's an issue with the way the formula gets divided into the between and within parts.
As a workaround, you can use a formula that includes some externality term and then set its coefficient to zero.

if you use `lighthergm::hergm` to estimate a model without externalities, the following error is raised:
```
Estimate between-block parameters
 parse(text = x, keep.source = FALSE) でエラー: 
  <text>:2:0:  想定外の入力の終端です 
1: g_logit ~  
```

### PR DESCRIPTION
**Pull request by komatsuna4747**
Fixed #2.

### CODE REVIEW

**Comment by justinian336** [comment]
@komatsuna4747 the error in the estimation is solved and the tests are passing, so it looks ok. I think we should fix the error in `simulate_hergm` in this PR as well.

**Comment by komatsuna4747** [comment]
@justinian336 Which error are you referring to?

**Comment by justinian336** [comment]
@komatsuna4747 it's the first error in #2. When you use `simulate_hergm` on a network without externalities you get the following error:

```
parse(text = x, keep.source = FALSE) でエラー: 
  <text>:2:0:  想定外の入力の終端です 
1: seed_network_within ~ 
   ^
```

**Comment by komatsuna4747** [comment]
@justinian336 
Sorry I missed that part. Let me check what causes the error and fix the bug.

**Comment by komatsuna4747** [comment]
Fixed the bug in `simulate_hergm` as well.

**Review by justinian336 — APPROVED** [review]
@komatsuna4747 
I checked that all tests run and that the simulation and estimation are performed without exceptions. Thanks for the quick fix!

**Pull request merged**
